### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by galbwe** [codefordenver/partner-finder#11]

**Comment by Nova791** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [API Documentation](https://trello.com/c/pZ5oAYwA/13-api-documentation)

**Comment by galbwe** [comment]
Got this to a point where frontend developers can see success responses for most of the endpoints. Some additions are still required, but I merged what I had so we have something to work with. Opened #87 for further api doc improvements.
