### ISSUE TITLE
PaginationControl upper page limit is always 100

### ISSUE THREAD

**Issue by galbwe** [codefordenver/partner-finder#134]
The upper page limit in the pagination control on the home page always displays 100, even if there are not 100 pages.

![Screen Shot 2021-09-28 at 11 54 59 PM](https://user-images.githubusercontent.com/20004072/135211170-2316fbd6-e120-465a-bd82-f87514c25c66.png)

Make the home component call the `/leads/n_pages` api endpoint and then render the PaginationControl component to show the correct number of pages.

**Comment by TueNguyen2911** [comment]
I'd like to work on this issue, please. Thank you!

**Comment by galbwe** [comment]
Hey @TueNguyen2911 I'll send you an invite to collaborate on the project.

**Comment by TueNguyen2911** [comment]
I've accepted, thank you!

**Comment by TueNguyen2911** [comment]
Hi @galbwe, after going through some struggle installing docker. This is what I have after running `docker ps` 

![image](https://user-images.githubusercontent.com/58532267/136131716-279d4f40-a1ff-4433-8be8-3747af1a3728.png)

Seems like it's missing the `front_end` container, it's not the same as the README.md. Am I missing something?

**Comment by TueNguyen2911** [comment]
It works! I've got the `front_end` container now. 

I have another question, I was trying to get an access token but encountered this error. I google for an answer but nothing seemed useful.
![image](https://user-images.githubusercontent.com/58532267/136134260-a82ca940-a534-433d-949a-c351f9a15e8d.png)

**Comment by galbwe** [comment]
So when the flask app starts in the development configuration, it logs an access token to the terminal. If the containers are running in the background, you should be able to view the logs with

```bash
docker compose logs api
```

The lines with the token should look similar to this

```bash
api_1       | [2021-10-06 03:12:03 +0000] [13] [INFO] To authenticate as user@gmail.com, include this header with the request:
api_1       |   Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJAZ21haWwuY29tIiwiZXhwaXJlcyI6IjIwMjEtMTAtMDdUMDM6MTI6MDMuNzExODE4KzAwOjAwIiwiYWRtaW4iOmZhbHNlfQ.Ls2CQ2nfsvXky7vn_PmUwuGKyMpC-ET6JH9n5Mmgtms
```

**Comment by TueNguyen2911** [comment]
Right, I've got the token. However, I don't see any react app running in my `localhost:1234`.

Thank you for bearing with me!

**Comment by galbwe** [comment]
All good.

First, what do you see in a browser when trying to visit `localhost:1234`?

Second, what is the output of `docker compose logs frontend` ?

**Comment by TueNguyen2911** [comment]
In `localhost:1234` , I see "this site can't be reached", basically nothing

And this is the output of `docker compose logs frontend` 
![image](https://user-images.githubusercontent.com/58532267/136136198-e3c60586-064d-49dd-8312-bae56c533e9e.png)

**Comment by galbwe** [comment]
Okay that looks like it might be the same problem that caused the container to shut down. I created https://github.com/codefordenver/partner-finder/issues/148 to address it. I think it should just be a matter of updating the frontend Dockerfile to look in the right directory for `parcel-bundler`. I'll see if I can get that resolved quickly.

**Comment by galbwe** [comment]
So I'm pretty sure this is the problem. In `frontend/Dockerfile`

`RUN yarn install`

should be 

`RUN yarn`

**Comment by galbwe** [comment]
Or at least it is a problem ... the container still doesn't start after that change.

**Comment by TueNguyen2911** [comment]
Yes I did try, react app is still not showing

**Comment by galbwe** [comment]
Okay, cool. I'm glad you are in.

I still have no idea why that fixes it though. I Initially thought `install` was only an npm command, but according to the [yarn docs](https://yarnpkg.com/getting-started/usage#installing-all-the-dependencies), `yarn` and `yarn install` do the same thing.

**Comment by TueNguyen2911** [comment]
Finally I'm in! I'm confused too, if `yarn` and `yarn install` do the same thing, why the container didn't start

**Comment by galbwe** [comment]
Not sure either. I'm leaving #148 open in case someone knows the solution.
