### ISSUE TITLE
Frontend Docker Container Does Not Start When First Cloning the Repo

### ISSUE THREAD

**Issue by galbwe** [codefordenver/partner-finder#148]
When cloning the repo and running `docker compose up --build` for the first time, the frontend container does not start. These logs lead me to believe that `parcel-bundler` needs to be installed as part of building the frontend docker image.

```bash
frontend_1  | yarn run v1.22.5
frontend_1  | $ parcel ./src/index.html --open --hmr-port=1235
frontend_1  | /bin/sh: parcel: not found
frontend_1  | error Command failed with exit code 127.
```

**Comment by w1shmast0ur** [comment]
Hi! Is there intention to run frontend in dev or you'd prefer to run the production build? I have solution for both and can help with this issue. Let me know which approach do you prefer and let me help you with that.

**Comment by galbwe** [comment]
Hi @w1shmast0ur we would like to run the frontend in dev. I believe the production dockerfile is being worked on in https://github.com/codefordenver/partner-finder/issues/99
