### ISSUE TITLE
Search SQL queries use string interpolation

### ISSUE THREAD

**Issue by galbwe** [codefordenver/partner-finder#170]
There are several sql queries in `leads.py` that are similar to this:

```python
            SELECT
                {columns}
            FROM leads
            WHERE to_tsvector(company_name) @@ to_tsquery('{search}')
            ORDER BY ts_rank(to_tsvector(company_name), '{search}')
            LIMIT :limit
            OFFSET :offset
```

They are susceptible to injection attacks because the `search` parameter comes from user input. Find a way to convert them to SQLAlchemy expression language, or try to use a placeholder for them, similar to `:limit` and `:offset`.

**Comment by galbwe** [comment]
@TueNguyen2911 I just assigned you

**Comment by TueNguyen2911** [comment]
Thank you!

**Comment by galbwe** [comment]
Yeah you'll need to run the backend using docker compose. See the [README](https://github.com/codefordenver/partner-finder#using-docker-compose) instructions on doing that.

We don't have automated unit tests at the moment. The best way to test right now is to use the swagger docs to make api calls. See [these instructions](https://github.com/codefordenver/partner-finder#using-docker-compose) for accessing the docs.

**Comment by TueNguyen2911** [comment]
Hi, I've encountered these problems 

![image](https://user-images.githubusercontent.com/58532267/137639946-eaea2625-4f3d-4b9b-bc9e-1de22a84f974.png)

![image](https://user-images.githubusercontent.com/58532267/137640086-eb2b9730-8483-4f47-9e38-28e58b1148fb.png)

I tried to ignore the `E501` error code in `.flake8` but it didn't work, I also saw the `max-line-length=120` but it still gave me error

**Comment by TueNguyen2911** [comment]
I have a few questions. 
1. How is your opinion on this change? After looking `sqlalchemy` up, instead of adding `search` to the textual query string using `format()`, I changed `'{search}'` into bound parameter `:search` and added `search` to `query_args` to pass into `execute()` so that in case of injection, it will auto-escape. 
```python 
query = text(
            """
            SELECT
                {columns}
            FROM leads
            WHERE to_tsvector(company_name) @@ to_tsquery(:search)
            ORDER BY ts_rank(to_tsvector(company_name), :search)
            LIMIT :limit
            OFFSET :offset
        """.format(
                columns=",".join(DEFAULT_LEAD_FIELDS),
            )
        )
        query_args = {"limit": limit, "offset": offset, "search": search}
```
2. I have `E501 line too long` errors, I commented linting options in  `.vscode/setting.json`  to bypass. What should I do with these errors? Will I be able to make a PR?

**Comment by TueNguyen2911** [comment]
I ran `backend/scripts/lint.sh` and it didn't show any error with `leads.py`, that's good. Thank you for telling me.
