### ISSUE TITLE
Replace Contact field with Email

### ISSUE THREAD

**Issue by galbwe** [codefordenver/partner-finder#182]
We have a "Contact" column in the table on the home page, but we do not have contact information for any rows:

```sql
select count(*) from leads where contact_name is not null;

-[ RECORD 1 ]
count | 0
```

However, we have email addresses that are not being used in the table

```sql
select count(*) from leads where email is not null;

-[ RECORD 1 ]
count | 758
```

Replace the "Contact" column with "Email". 

![Screen Shot 2021-10-14 at 7 57 31 AM](https://user-images.githubusercontent.com/20004072/137332422-c7138bff-7776-4f12-b4df-f363745b14f0.png)

Include a link in each row with [href="mailto..."](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#e-mail_links) that includes the provided email address. The email address can be accessed by the `email` property of the `leads` object.

If no email address is available for a lead, display nothing in the email column for that row.

If you want to be super fancy, use an icon instead of email text. The `Email` icon from the [MaterialUI docs](https://mui.com/components/material-icons/) seems like a good candidate.

**Comment by Safwan310** [comment]
Hey, can I do this?

**Comment by galbwe** [comment]
Sure @Safwan310 ! I'll assign you.
