### ISSUE TITLE
Remove python exceptions that can be sent in api responses

### ISSUE THREAD

**Issue by galbwe** [codefordenver/partner-finder#190]
There is at least one return statement in the backend that looks like this;

```python
except SomeException e:
    return {"message": f"There was a problem: {e}"}, 422
```

CodeQL issues warnings here because it's bad practice to send language / framework specific details to a user.

Find other places where this is an issue. Update these return statements to not include the python exeption and instead use a message that gets a similar point across.

**Comment by kaleeaswari** [comment]
@galbwe can I get this assigned?
