### ISSUE TITLE
Add inline assignee editing

### ISSUE THREAD

**Issue by galbwe** [codefordenver/partner-finder#226]
In the assignee main table on the homepage, add a component for assigning a user to a lead. One approach would be to use the material ui [Autocomplete](https://v4.mui.com/components/autocomplete/) component. The user data can be retrieved using the `GET /users` endpoint. Editing leads can be accomplished with the `PUT /leads/{id}` endpoint.

**Comment by pthan1** [comment]
I'd like to work on this issue
