### ISSUE TITLE
Script to write Colorado Nonprofits Association data to postgres

### ISSUE THREAD

**Issue by galbwe** [codefordenver/partner-finder#41]
Add a job to `tasks.py` that writes scraped colorado nonprofits data to a postgres database. It can either write from a saved csv or scrape the data each time it is run before writing. There is currently no aws postgres instance to write to, so use the local development database in docker-compose for now. 

Then add a new python file to the `database` directory to serve as a top level entry script. You can follow the pattern established in `scrape_socrata.py` and `create_dev_users.py` for this. 

Finally, make sure the new python script is run in `docker-compose.yml` under the `command` keyword.

**Comment by galbwe** [comment]
@silkylaroux are you still working on this?

**Comment by Nova791** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Script to write CNA data to Postgres](https://trello.com/c/Wn3XtCNr/8-script-to-write-cna-data-to-postgres)

**Comment by galbwe** [comment]
Addressed by #78
