### ISSUE TITLE
Set up Github Actions

### ISSUE THREAD

**Issue by galbwe** [codefordenver/partner-finder#7]

**Comment by galbwe** [comment]
Backend linting has been set up already. We need a frontend linter job to run also.

**Comment by galbwe** [comment]
Frontend linter now runs a prettier check and eslint check. 

We should also add to the backend linting job to check that black was run.

**Comment by galbwe** [comment]
Linter checks are set up. We probably need to work on unit and integration tests and setting up an AWS project before continuing with this issue.

**Comment by iatenine** [comment]
Recommend closing as stale
