### ISSUE TITLE
Create Frontend Skeleton

### ISSUE THREAD

**Issue by galbwe** [codefordenver/partner-finder#81]
- Delete the existing frontend directory.
- Create a new frontend project using create-react-app, following the same pattern
- Identify components we will need in the project. Refer to the [mockup](https://www.figma.com/file/qcUUcWrSzEAmDZWJLvzXD5/Untitled?node-id=0%3A1)
- Create a `components` directory with a js file for each component.

**Comment by Nova791** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Frontend Skeleton](https://trello.com/c/Ma6DfDyO/4-create-frontend-skeleton)
